### ISSUE TITLE
CNI hook causes panic

### ISSUE THREAD

**Issue by jimmidyson** [d2iq-labs/capi-runtime-extensions#12]
```
I0202 19:07:48.494140       1 handlers.go:44] "AfterControlPlaneInitialized is called"
2023/02/02 19:07:48 http2: panic serving 10.244.0.8:57042: runtime error: invalid memory address or nil pointer dereference
goroutine 530 [running]:
net/http.(*http2serverConn).runHandler.func1()
	net/http/h2_bundle.go:5903 +0x125
panic({0x15354c0, 0x24b3b40})
	runtime/panic.go:884 +0x212
[sigs.k8s.io/cluster-api/cmd/clusterctl/client/repository.NewTemplate({{0x23c8360](http://sigs.k8s.io/cluster-api/cmd/clusterctl/client/repository.NewTemplate({{0x23c8360), 0x1ba, 0x1ba}, {0x0, 0x0}, {0x1949900, 0x250e480}, {0xc0003b2840, 0x7}, 0x0})
	[sigs.k8s.io/cluster-api@v1.3.3/cmd/clusterctl/client/repository/template.go:116](http://sigs.k8s.io/cluster-api@v1.3.3/cmd/clusterctl/client/repository/template.go:116) +0x156
[github.com/d2iq-labs/capi-runtime-extensions/pkg/addons.objsFromTemplate({0x23c8360](http://github.com/d2iq-labs/capi-runtime-extensions/pkg/addons.objsFromTemplate({0x23c8360)?, 0xc00015afe0?, 0x719810?}, {0xc0003b2840?, 0x0?})
	[github.com/d2iq-labs/capi-runtime-extensions/pkg/addons/crs.go:33](http://github.com/d2iq-labs/capi-runtime-extensions/pkg/addons/crs.go:33) +0xb8
[github.com/d2iq-labs/capi-runtime-extensions/pkg/addons.crsObjsFromTemplates({0xc0003b2840](http://github.com/d2iq-labs/capi-runtime-extensions/pkg/addons.crsObjsFromTemplates({0xc0003b2840), 0x7}, {0xc00015b070, 0x3, 0x26?})
	[github.com/d2iq-labs/capi-runtime-extensions/pkg/addons/crs.go:17](http://github.com/d2iq-labs/capi-runtime-extensions/pkg/addons/crs.go:17) +0xd2
[github.com/d2iq-labs/capi-runtime-extensions/pkg/addons.CNIForCluster(...)](http://github.com/d2iq-labs/capi-runtime-extensions/pkg/addons.CNIForCluster(...))
	[github.com/d2iq-labs/capi-runtime-extensions/pkg/addons/cni.go:29](http://github.com/d2iq-labs/capi-runtime-extensions/pkg/addons/cni.go:29)
[github.com/d2iq-labs/capi-runtime-extensions/pkg/handlers/lifecycle.(*ExtensionHandlers).DoAfterControlPlaneInitialized(0xc00059d160](http://github.com/d2iq-labs/capi-runtime-extensions/pkg/handlers/lifecycle.(*ExtensionHandlers).DoAfterControlPlaneInitialized(0xc00059d160), {0x1948a00, 0xc000844780}, 0xc000461180, 0xc0002381c0)
	[github.com/d2iq-labs/capi-runtime-extensions/pkg/handlers/lifecycle/handlers.go:49](http://github.com/d2iq-labs/capi-runtime-extensions/pkg/handlers/lifecycle/handlers.go:49) +0x1b6
```

**Comment by dkoshkin** [comment]
Fixed with https://github.com/d2iq-labs/capi-runtime-extensions/pull/13
